resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 60000
        permittedNumberOfCallsInHalfOpenState: 4
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: false
        minimumNumberOfCalls: 10
        maxWaitDurationInHalfOpenState: 1000
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        waitDurationInOpenState: 10000
    instances:
      # API Server
      findUser:
        baseConfig: default
      findUserProfile:
        baseConfig: default
      findUserCount:
        baseConfig: default
      findContents:
        baseConfig: default
      findContentsCount:
        baseConfig: default
      signInUser:
        baseConfig: default
      signInAdmin:
        baseConfig: default
      signOut:
        baseConfig: default
      signUp:
        baseConfig: default
      removeUser:
        baseConfig: default
      tokenRemoveUser:
        baseConfig: default
      updateUser:
        baseConfig: default
      createContents:
        baseConfig: default
      updateContents:
        baseConfig: default
      findDashboardCount:
        baseConfig: default
      clientHealth:
        baseConfig: default
      # Design Server
      findThemeItem:
        baseConfig: default
      findComponent:
        baseConfig: default
      findLayout:
        baseConfig: default
      findStyle:
        baseConfig: default
      findTheme:
        baseConfig: default
      findComponentCount:
        baseConfig: default
      findLayoutCount:
        baseConfig: default
      findStyleCount:
        baseConfig: default
      findThemeCount:
        baseConfig: default
      removeComponent:
        baseConfig: default
      removeLayout:
        baseConfig: default
      removeStyle:
        baseConfig: default
      removeTheme:
        baseConfig: default
      designHealth:
        baseConfig: default